### ISSUE TITLE
Homepage URL on 404.html is broken

### ISSUE THREAD

**Issue by sauerj** [AngeloStavrow/indigo#20]
Hey, thanks for your work. I like your theme.

I noticed that on the 404.html page the link back to the homepage is broken.
Instead of a valid URL a link to `Page("Homepage name")` is created.

I have a fix ready and can submit a pull request if you want.

**Comment by AngeloStavrow** [comment]
Thanks for reporting this, and for your kind words!

If you've got a pull request ready, please go ahead and submit it — I'll review it ASAP.
