### ISSUE TITLE
Lost </div> in 404.html

### ISSUE THREAD

**Issue by sauerj** [AngeloStavrow/indigo#21]
By inspecting the source of the generated 404.html, Firefox noticed a lost `</div>` just after the `</section>` from `layouts/404.html`

This is caused by `layouts/partials/footer.html:2` which is closing the "content" `<div>` which does not exist in `layouts/404.html`

**Comment by AngeloStavrow** [comment]
Thanks for your report! I'll fix this shortly, unless you have a PR ready for submitting.

**Comment by sauerj** [comment]
No, unfortunately I do not have a PR ready. I was not sure how you want to address this issue.

**Comment by AngeloStavrow** [comment]
That's fair enough. Let me consider how to best approach this. The more I think about it, I realize that I'm not overly fond of having a random `</div>` at the top of a partial.
