### ISSUE TITLE
Static files can not be accessed when baseURL contains a path

### ISSUE THREAD

**Issue by sauerj** [AngeloStavrow/indigo#27]
When the `baseURL` configuration contains a path eg: https://www.example.org/user/example/ files under `/static` can not be found.

I set up a [testsite](https://www.oxygin.net/themes/indigo) with `baseURL = "https://www.oxygin.net/themes/indigo"` in config.toml

The icons and fonts can not be loaded because the site looks under the path `/icons` `/fonts` instead of `/themes/indigo/icons` etc.

**Comment by AngeloStavrow** [comment]
Thanks for the report! I’ll dig into the Hugo docs to see what the best path forward is.

**Comment by AngeloStavrow** [comment]
This repros on the Hugo Themes [demo site]() so it'd be really nice to fix ASAP.

Fixing this on the icons as discussed in #23 should be pretty straightforward — prefixing the `img src` with `baseURL` (or some variant like `absURL` or `relURL`, maybe) should fix this in the **social.html** partial.

However, the tricky part is going to be the fonts, as I'm not sure that I can add Hugo templating code to **style.css**. This will require more investigation.

**Comment by AngeloStavrow** [comment]
Okay, I think the solution for using `baseURL` in CSS for loading our fonts lies in plain-text partials, as described in the [release notes for Hugo 0.20.2](https://github.com/gohugoio/hugo/releases/tag/v0.20.2). We can pull the `@font-face` declarations out of the main **style.css** file, and put them into **layouts/partials/fonts.css**, and then load them into the page like so:

```
<head>
    …
    <style type="text/css">{{ partial "fonts.css" . | safeCSS }}</style>
    <link rel="stylesheet" href="{{ .Site.BaseURL }}css/style.css" />
    …
</head>
```

When I test this in the hugoThemes site, it seems to work properly.

**Comment by AngeloStavrow** [comment]
Merged into `master`.

**Comment by sauerj** [comment]
@AngeloStavrow Sorry for the late test, I can confirm that everything works as expected.

**Comment by AngeloStavrow** [comment]
Glad to hear it, thanks!
