### ISSUE TITLE
Headings h1 and h2 are interchanged

### ISSUE THREAD

**Issue by kuleszdl** [AngeloStavrow/indigo#41]
First of all, thank you a lot for making this great theme available! How,ever I noticed that the style of the headings seems to be a bit off:

**Describe the bug**
Headings of level h1 appear smaller than those of level h2.

**To Reproduce**

Build a site using both headings, e.g.:

```
# Heading 1

text

## heading 2

text
```

or

```
Heading1
=======

text

Heading 2
-------------

text
```

**Expected behavior**
Heading 1 should be larger than heading 2.

**Screenshots**

![screen](https://user-images.githubusercontent.com/1338148/56864121-011f2880-69bf-11e9-91e8-abbb6e5f3a8b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 60.x (ESR)

**Additional context**
Could be worked around by using the syntax the other way round, however, switching themes later would be cumbersome.

**Comment by AngeloStavrow** [comment]
Whoopsie, yeah. I’m using `h1`s for the title and should apply the same styling (or `font-size`, at least) in the article body too.
