### ISSUE TITLE
Getting posts to appear on the main page is oddly confusing

### ISSUE THREAD

**Issue by findgriffin** [AngeloStavrow/indigo#56]
**Describe the bug**
I just spent a few hours trying to figure out how to get my posts to appear on the main page of a new blog I'm creating.

**To Reproduce**
1. Follow Hugo [Quick Start](https://gohugo.io/getting-started/quick-start/) guide.
2. Use [Indigo](https://themes.gohugo.io/indigo/) theme.
3. Create a post as per the quick start guide example e.g. `hugo new posts/my-first-post.md`
4. Start server and navigate to `localhost:1313`
5. Observe no posts. The paginator will say "page 1 of 0".
6. Observe that the post does exist at `localhost:1313/posts/my-first-post`
7. Add `type: "post"` to `my-first-post.md`
8. (optional) Google for 2-3 hours about how Hugo works.
9. Observe that it now shows up at `localhost:1313`

I'm pretty sure the issue is due to this line in `list.html`:
```
{{ range $index, $page := (.Paginate (where .Site.RegularPages "Type" "post")).Pages }}
```

**Expected behavior**
My posts to appear on the main page of my blog when I follow the Hugo quickstart guide and the Indigo docs.

**Proposed Fix(es)**
I'm not that familiar with Hugo, but to my mind you could do any of the following:
1. Add a note to the Indigo docs
2. Add a custom Indigo archetype that sets `type: post`
3. Change `list.html` to accept post OR posts type.

Anyway, thanks for creating / maintaining this theme.

Cheers

**Comment by AngeloStavrow** [comment]
Okay, as part of the work I'm doing in #57, it looks like we can incorporate a new `mainSections` variable in the config file to do this. More detail in the Hugo docs [here](https://gohugo.io/functions/where/#mainsections).

Unless it proves to be spectacularly more complicated than the docs make it appear, I think I'll be able to push a fix for this out by tomorrow evening. :)

**Comment by AngeloStavrow** [comment]
Closed by #62

**Comment by findgriffin** [comment]
Thanks so much!

David

Phone (USA): +1 206 307 1002

**Comment by infominer33** [comment]
idk why, but I can only get it to work if I **don't** include the mainsections param
