### ISSUE TITLE
Broken Link in ReadMe

### ISSUE THREAD

**Issue by Mike-EEE** [AngeloStavrow/indigo#69]
Nice theme. :D  I have selected it and am incorporating it for my next project and have been following the instructions in the `README`.  In doing so, I've encountered what appears to be a broken link here:

https://github.com/AngeloStavrow/indigo/blob/master/README.md#L21

I've done some searching and couldn't find its obvious replacement, so I wanted to let you know.

Continue the great work! 👍

**Comment by AngeloStavrow** [comment]
Thanks for the kind words, and for the heads up!

To confirm, that's the link that's supposed to point to "theme-installation instructions on the Hugo website", right? It looks like the Hugo team changed their docs, so I'll fix that.

In the meanwhile, check out their Quickstart, specifically the section on how to add a Hugo theme: https://gohugo.io/getting-started/quick-start/

**Comment by AngeloStavrow** [comment]
Fixed in 58177f2

**Comment by Mike-EEE** [comment]
> To confirm, that's the link that's supposed to point to "theme-installation instructions on the Hugo website", right?

Correct!  Thank you much!
