### ISSUE TITLE
Support specifying indieweb endpoints

### ISSUE THREAD

**Issue by kasuboski** [AngeloStavrow/indigo#73]
I saw params.endpoints section for config.toml referenced https://web-work.tools/indieweb/indigo/features/.

It doesn't seem like that is implemented in this theme, however.

Am I missing something? Currently, have an issue because [Aperture](https://aperture.p3k.io/docs) is expecting the token_endpoint to be set.

**Comment by AngeloStavrow** [comment]
I _think_ that might be something that was added by @infominer33 to their own site — good catch!

**Comment by AngeloStavrow** [comment]
Closed by #74 — thanks again!
