### ISSUE TITLE
CODE block breaks in MS Edge

### ISSUE THREAD

**Issue by fu-sen** [AngeloStavrow/indigo#78]
I referenced the following on MS Edge:
https://themes.gohugo.io//theme/indigo/post/markdown-syntax/

As a result, one line space is left in CODE block:
![スクリーンショット 2020-02-17 13 02 10](https://user-images.githubusercontent.com/5434159/74623046-67f81300-5186-11ea-8cb2-4908eab1b1ba.jpg)

Chrome and Firefox don't have this, but some Windows users will care.

**Comment by fu-sen** [comment]
found this solution:
```
code {
    display: block;
}
```

![スクリーンショット 2020-02-17 17 05 45](https://user-images.githubusercontent.com/5434159/74634813-021c8300-51a8-11ea-86ef-1b55c477da7a.jpg)

CSS may need additional tweaking, but it is a separate issue.

**Comment by AngeloStavrow** [comment]
Thanks for opening this! Code blocks in general could be improved, as they don't play very nicely with Hugo's highlight shortcodes either.

**Comment by AngeloStavrow** [comment]
I think this was fixed at some point, maybe with the new Markdown renderer? I don't see this extra-linebreak issue in Edge anymore (the syntax highlighting in #89 is still a problem, though, and I'm fixing it now).

Closing as `wontfix`, but please don't hesitate to re-open if you continue to see an issue!
