### ISSUE TITLE
Hosting on Github Pages results in Mixed SSL content

### ISSUE THREAD

**Issue by TGNYC** [AngeloStavrow/indigo#79]
Hello,

I am trying to host my blog using the Indigo theme on Github Pages. However, whenever I force HTTPS through the Github Pages settings, some of the site elements, such as the images (logos, etc.) break. Your help with fixing this problem would be much appreciated.

Thanks!

**Comment by AngeloStavrow** [comment]
@TGNYC That's curious. I'm enforcing HTTPS on my own GitHub Pages site and I don't any Mixed SSL content. Do you have a link or a repo I can look at to investigate?

**Comment by AngeloStavrow** [comment]
I’m going to close this for now, but feel free to re-open with more info!
