### ISSUE TITLE
make navigation configurable

### ISSUE THREAD

**Issue by damnms** [AngeloStavrow/indigo#93]
it would be nice if the navigation menu's could be configurable. 
i would like to add 4-5 other menu entries like "faq" "about" "mail" "register" etc.

**Comment by AngeloStavrow** [comment]
Hey @damnms, thanks for the feedback! Have you seen [this page](https://hello-indigo.glitch.me/adding-menu-items/) on how you can create pages to be added to the top-bar menu?

> Indigo supports adding a simple navigation-style menu items across the top of the site. To do so, simply add a `menu: "main"` entry in your page’s front matter (TOML format shown).
> 
> If no date is included in the front matter, then the published date won’t be shown (as in this page).

(This should be in the README, but it's not, and I'm making a note to fix that.)

Does that help, or did I misunderstand your request?

**Comment by damnms** [comment]
thanks, thats what i was looking for
